server/models/event.js, server/models/user.js
Created DB Models for Users and Events
=> Created Event and User Models

client/modules/Event/EventActions.js, package-lock.json
there was a bogus action in events now fixed!
=> changed to correct http post type

client/modules/App/components/DateSearch/DateSearch.jsx, client/modules/App/components/Header/SearchBar/index.jsx, client/modules/App/components/Header/index.jsx, server/dummyEvents.js
We're now utilizing the fetch events action method and plugged it into redux within the autocomplete component. Now instead of the array of objects that autocomplete had hard coded, the even list array is now plugged in.
=> Autocomplete data now pops from database

client/modules/Auth/AuthActions.js, package-lock.json, server/controllers/user.controller.js, server/dummyEvents.js, server/models/event.js, server/models/user.js
Still working on getting some bugs figured out. At the moment although
it is saving the users it is not checking if the user exists and is
creating duplicates.
=> Added Firebase Info to the Persistance Layer under the User Model.

client/modules/App/components/DateSearch/DateSearch.jsx, client/modules/Event/EventActions.js, server/controllers/event.controller.js, server/routes/event.routes.js
The only hurdle left to search (and implementing this in other places) is the fact that materialize doesn't seem to interact with react's onChange event. Any ideas?
=> Search by date functionality almost there

client/modules/App/components/DateSearch/DateSearch.jsx
the big catch here is its working by putting a lot of state
into the dom. obviously not good but I'll do some office hrs
today to get it straightened out.
=> date search works

client/modules/App/components/Header/index.jsx, client/modules/App/components/SearchForm/SearchEventDate.jsx, client/modules/App/components/SearchForm/SearchEventName.jsx, client/modules/App/components/SearchForm/index.jsx, client/modules/Event/EventActions.js, package-lock.json, package.json, server/controllers/event.controller.js, server/routes/event.routes.js
So the search is now working for the second area of the events list. NOT on the place holder area above on games/, this is just the general area. The full events list.
=> Header search

client/modules/App/components/SearchForm/SearchEventDate.jsx, client/modules/App/components/SearchForm/index.jsx, client/modules/Event/components/EventList/index.jsx, client/modules/Event/pages/EventDetailPage/EventDetailPage.js
connections between the code and the store and planning my approach to
tackle my story. No solid code pushed, just formatting as I went along.
=> I sat around rooting through the directories attempting to make

client/modules/App/components/Header/index.jsx, client/routes.js
Still need to create functionality of view my events. At the moment
they just appear in the top of the EventListPage Section
=> Changed the home page to default to EventListPage

client/modules/App/components/SearchForm/SearchEventDate.jsx, client/modules/App/components/SearchForm/index.jsx, client/modules/Event/EventActions.js, server/controllers/event.controller.js
Trying to search by ISO dates wasn't working because we're not storing
dates as iso dates! we really should be though. I think this may be
because models don't have correct validation and our controller probably
needs a date sanitization/formatting function.
=> We pulled date search and fixed event name search

webpack.config.dev.js
HMR was broken due to our webpack config of publicPath=0.0.0.0:8000
to remedy the situation we added a const for ASSET_PATH, plugged it in
and then set it into the publicPath key's value. See output.publicPath
on webpack.config.dev.js:27
=> Fixed HMR, because reasons

client/modules/Event/components/EventCreateWidget/EventCreateWidget.js, client/modules/Event/pages/EventListPage/EventListPage.js, package-lock.json
Form was not submitting information into the correct fields in the db.
Lesson: the order of the params matter.
Also fixed a small issue with missing placeholder text for the time
picker.
=> Fixed an Issue with CreateEventWidget.

client/modules/Event/EventActions.js, client/modules/Event/EventReducer.js, client/modules/Event/pages/EventDetailPage/EventDetailPage.js, server/controllers/event.controller.js, server/routes/event.routes.js
This was all done with a functional component with state being
deal with very lower in the component hierarchy. I believe we will need
a class or smart component to make this page more featurefull.
=> completed vertical slice story to join an event

client/modules/Event/components/HostEditingInterface/EventEditForm/index.jsx, client/modules/Event/components/HostEditingInterface/ExperimentalEditComponent/index.jsx
There are no sanity checks. We'll likely need to, when we develop them,
throw the sanity in this component that we put in the creation widget.
=> Followed up on all the endpoints I created that allow us to edit events.

client/modules/Event/components/HostEditingInterface/EventEditForm/index.jsx, client/modules/Event/components/UserJoinWidget/index.jsx
and update the correct components.
=> Quick fix regarding the edit form. Now all forms should auto-populate

client/modules/Event/components/EventListItem/EventListItem.js, package-lock.json
Just pulls the length of the attendees and places it as the numerator
above the number of slots (denominator).
=> Updated Event List to display the attendees that are signed up.

client/modules/Event/components/EventListItem/EventListItem.js, client/modules/Event/components/EventPageDetails/EventDetails.js
Dates are now being displayed in (MMM, DD, YYYY) format.
=> Implemented MomentJS to format date fields in Event List and Details

client/modules/App/images/.directory, server/dummyEvents.js, server/server.js
- Fixed the issue with the favicon Janet was having. Just required importing the image to server js and passing it as a variable into the URL. 
- Added 15 more seeded events, all in august or further out.
=> Fixed Favicon Import and Added More Seed Data

client/modules/Auth/components/SignInScreen/App.css, client/modules/Auth/components/SignInScreen/SignInScreen.js, server/dummyEvents.js
- Fixed Link for Brand Logo to Home Page
- Fixed an issue with a duplicate seed data
=> Fixed Seed Data Issue with Duplicate CUID

client/modules/Event/components/EventList.js, client/modules/Event/components/EventList/EventList.js, client/modules/Event/components/EventListItem/EventListItem.js
- Set card sizes to display in a row.
- Set responsive classes to S12 M6 and L4 and XL4
- Set card height to be uniform by changing the adding the large
class to the card class
=> Made the following UI changes to the cards:

client/modules/App/components/SearchForm/SearchEventName.js, client/modules/App/components/SearchForm/SearchForm.js, client/modules/Event/components/EventListItem/EventListItem.js, client/modules/Event/components/EventPageDetails/Host/FormEditWrap/EventForm/EventForm.js
sanctioned(tm) gametypes. This effectively reduces autocomplete
functionality; however, whenever you type a character the search reaches
to the back end and populates the list based on what you typed in so
far, so you can type in any custom search
Actual search button is also now redundant
=> Cleansed the auto-complete search functionality to return only

client/modules/Event/components/EventListItem/EventListItem.css, client/modules/Event/components/EventPageDetails/EventDetails.js, client/modules/Event/components/EventPageDetails/Guest/Guest.js, client/modules/Event/components/EventPageDetails/Guest/Join/Join.js, client/modules/Event/components/EventPageDetails/Guest/Join/join.css, client/modules/Event/components/EventPageDetails/Host/Attendees/Attendees.js, client/modules/Event/components/EventPageDetails/Host/Delete/Delete.js, client/modules/Event/components/EventPageDetails/Host/HostDetails.css, client/modules/Event/components/EventPageDetails/Host/HostDetails.js, package-lock.json, package.json
- Edited Layout and CSS for components included in EventDetail Page
=> EventDetail Page Overhaul (see below)

client/modules/Event/EventReducer.js, client/modules/Event/components/EventChat/ChatSubscription.js, client/modules/Event/components/EventPageDetails/Guest/Guest.js, client/modules/Event/components/EventPageDetails/Guest/NotLoggedIn/NotLoggedIn.js, client/modules/Event/components/EventPageDetails/HostGuest/HostGuest.js, client/modules/Event/pages/EventDetailPage/EventDetailPage.js
We were not making use of selector pattern for member/host/logged in
user statuses. We were setting local state with this.setState() which is
only ok when dealing with component state that doesn't need to persist
past a page refresh.
=> Fixed state issues with user type/state

client/modules/Event/components/EventListItem/EventListItem.css, client/modules/Event/components/EventListItem/EventListItem.js, client/modules/Event/components/EventPageDetails/EventDetails.js, client/modules/Event/pages/EventDetailPage/EventDetailPage.js
=> Date hotfix
